added docker start/stop, requierments duplicate file deleted
ch-covid-19/analysis-scripts pull request #19
Opened 2020-03-31 21:35 UTC by pksec

- added docker start/stop script
- updated readme
- updated pythonpath

2020-04-02 21:38 UTC, nuffer requested changes

2020-04-02 21:38 UTC, nuffer commented on python_install.sh
> +export PYTHONPATH=$PWD/analysis:$PYTHONPATH
This will have an effect only on the current terminal session. So I don't know why you need this in the install script.

2020-04-03 06:50 UTC, pksec commented on python_install.sh
> +export PYTHONPATH=$PWD/analysis:$PYTHONPATH
Yeah, you're right. I removed it. Now it should be ok.

2020-04-03 07:54 UTC, nuffer approved these changes

2020-04-03 07:54 UTC, merged